# -*- coding: utf-8 -*-
"""traffic_accidents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wr9jiHkIMjiFxcXZimTx96GPd-nNvOZG
"""

import pandas as pd
df = pd.read_csv("45_traffic_accidents.csv")
df.head()

df.shape
df.info()
df.describe()

df.isnull().sum()

import matplotlib.pyplot as plt

df.hist(figsize=(12,10))
plt.tight_layout()
plt.show()

import seaborn as sns

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

sns.histplot(df["severity_1to3"], kde=True)
plt.title("Target Distribution (Accident Severity)")
plt.show()

X = df.drop(["severity_1to3", "id"], axis=1) # Drop target AND id column
y = df["severity_1to3"]

X = pd.get_dummies(X, drop_first=True)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Use Classifier instead of Regressor
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report
import numpy as np

print("Classification Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

import pandas as pd

importance = rf.feature_importances_
feat_imp = pd.Series(importance, index=X.columns)

feat_imp.nlargest(10).plot(kind='barh')
plt.title("Top Features")
plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix (Severity Prediction)")
plt.show()

# --- Save Model ---
import joblib
joblib.dump(rf, 'model.pkl')
joblib.dump(list(X.columns), 'model_columns.pkl')
print("Model and columns saved successfully!")

